# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ydwNvzoZrvUCnnf31t0QxcqoGJqaIUh

First, we need to import the necessary libraries: `requests` for making HTTP requests to fetch web pages, `BeautifulSoup` for parsing HTML content, and `pandas` for data manipulation and saving to CSV.
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

"""Next, let's define a function to perform the web scraping. This function will fetch the content of the given URL and extract text from common elements like paragraphs, headings, and lists. It will return a dictionary of the scraped data."""

def scrape_website_text(url):
    """
    Scrapes text content from a given URL.
    Extracts text from common elements like paragraphs, headings, and list items.
    """
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()  # Raise an exception for HTTP errors
    except requests.exceptions.RequestException as e:
        print(f"Error fetching URL {url}: {e}")
        return None

    soup = BeautifulSoup(response.text, 'html.parser')

    # Initialize lists to store different types of text
    headings = []
    paragraphs = []
    list_items = []
    all_text = []

    # Extract headings
    for h in soup.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6']):
        text = h.get_text(strip=True)
        if text:
            headings.append(text)
            all_text.append(text)

    # Extract paragraphs
    for p in soup.find_all('p'):
        text = p.get_text(strip=True)
        if text:
            paragraphs.append(text)
            all_text.append(text)

    # Extract list items
    for li in soup.find_all('li'):
        text = li.get_text(strip=True)
        if text:
            list_items.append(text)
            all_text.append(text)

    # Prepare data for DataFrame
    data = {
        'URL': url,
        'Headings': '; '.join(headings),
        'Paragraphs': '\n\n'.join(paragraphs),
        'List Items': '; '.join(list_items),
        'All Extracted Text': '\n\n'.join(all_text) # Combine all text for a general overview
    }
    return data

"""Now, let's use the defined function to scrape the data from the target URL. I'll use the `target_url` variable already in your environment, which is `'https://www.pakwheels.com/used-cars/lahore/24858'`. You can modify the `url_to_scrape` variable if you want to scrape a different website."""

url_to_scrape = target_url # Using the predefined target_url
# If you want to use a different URL, uncomment the line below and change the URL
# url_to_scrape = 'https://www.example.com'

print(f"Scraping data from: {url_to_scrape}")
scraped_data = scrape_website_text(url_to_scrape)

if scraped_data:
    # Convert the dictionary to a pandas DataFrame
    df_scraped = pd.DataFrame([scraped_data])
    display(df_scraped.head())
else:
    print("No data was scraped or an error occurred.")

"""Finally, we will save the scraped data to a CSV file named `scraped_website_data.csv`."""

if 'df_scraped' in locals() and not df_scraped.empty:
    output_filename = 'scraped_website_data.csv'
    df_scraped.to_csv(output_filename, index=False, encoding='utf-8')
    print(f"Scraped data saved to '{output_filename}'")
else:
    print("No DataFrame to save or DataFrame is empty.")